//     __ _____ _____ _____\n//  __|  |   __|     |   | |  JSON for Modern C++\n// |  |  |__   |  |  | | | |  version 3.12.0\n// |_____|_____|_____|_|___|  https://github.com/nlohmann/json\n//\n// SPDX-FileCopyrightText: 2013-2025 Niels Lohmann <https://nlohmann.me>\n// SPDX-License-Identifier: MIT\n\n#include <doctest/doctest.h>\n\n#include <nlohmann/json.hpp>\n\nusing json = nlohmann::json;\n\nTEST_CASE("parse state save and restore")\n{\n    // Test case 1: Save and restore state during parsing\n    std::string json_str = R"({"name": "John", "age": 30, "city": "New York"})";
    json::input_adapter_t ia(json_str);\n    json::parser<json> parser(std::move(ia));\n    json result;\n    \n    // Parse part of the JSON\n    auto state = parser.save_state();\n    parser.parse(false, result);\n    \n    // Check that the result is correct\n    CHECK(result["name"] == "John");\n    CHECK(result["age"] == 30);\n    CHECK(result["city"] == "New York");\n    \n    // Test case 2: Save state before parsing and restore it\n    std::string json_str2 = R"({"name": "Jane", "age": 25, "city": "London"})";
    json::input_adapter_t ia2(json_str2);\n    json::parser<json> parser2(std::move(ia2));\n    json result2;\n    \n    // Save state before parsing\n    auto state2 = parser2.save_state();\n    \n    // Parse the JSON\n    parser2.parse(false, result2);\n    \n    // Check that the result is correct\n    CHECK(result2["name"] == "Jane");\n    CHECK(result2["age"] == 25);\n    CHECK(result2["city"] == "London");\n    \n    // Test case 3: Save state during parsing and restore it to parse another JSON\n    std::string json_str3 = R"({"name": "Bob", "age": 40, "city": "Paris"})";
    json::input_adapter_t ia3(json_str3);\n    json::parser<json> parser3(std::move(ia3));\n    json result3;\n    \n    // Save state during parsing\n    auto state3 = parser3.save_state();\n    \n    // Parse the JSON\n    parser3.parse(false, result3);\n    \n    // Check that the result is correct\n    CHECK(result3["name"] == "Bob");\n    CHECK(result3["age"] == 40);\n    CHECK(result3["city"] == "Paris");\n}\n\nTEST_CASE("parse state with memory limit")\n{\n    // Test case 1: Save state with memory limit\n    std::string json_str = R"({"name": "John", "age": 30, "city": "New York"})";
    json::input_adapter_t ia(json_str);\n    json::parser<json> parser(std::move(ia));\n    \n    // Set memory limit\n    parser.set_memory_limit(1024 * 1024);\n    \n    // Save state\n    auto state = parser.save_state();\n    \n    // Check that memory limit is saved\n    CHECK(state.memory_limit == 1024 * 1024);\n    \n    // Test case 2: Restore state with memory limit\n    std::string json_str2 = R"({"name": "Jane", "age": 25, "city": "London"})";
    json::input_adapter_t ia2(json_str2);\n    json::parser<json> parser2(state, std::move(ia2));\n    json result2;\n    \n    // Parse the JSON\n    parser2.parse(false, result2);\n    \n    // Check that the result is correct\n    CHECK(result2["name"] == "Jane");\n    CHECK(result2["age"] == 25);\n    CHECK(result2["city"] == "London");\n}\n\nTEST_CASE("parse state with relative memory limit")\n{\n    // Test case 1: Save state with relative memory limit\n    std::string json_str = R"({"name": "John", "age": 30, "city": "New York"})";
    json::input_adapter_t ia(json_str);\n    json::parser<json> parser(std::move(ia));\n    \n    // Set relative memory limit\n    parser.set_relative_memory_limit(0.5);\n    \n    // Save state\n    auto state = parser.save_state();\n    \n    // Check that relative memory limit is saved\n    CHECK(state.relative_memory_limit == 0.5);\n    \n    // Test case 2: Restore state with relative memory limit\n    std::string json_str2 = R"({"name": "Jane", "age": 25, "city": "London"})";
    json::input_adapter_t ia2(json_str2);\n    json::parser<json> parser2(state, std::move(ia2));\n    json result2;\n    \n    // Parse the JSON\n    parser2.parse(false, result2);\n    \n    // Check that the result is correct\n    CHECK(result2["name"] == "Jane");\n    CHECK(result2["age"] == 25);\n    CHECK(result2["city"] == "London");\n}\n\nTEST_CASE("parse state with mixed memory limits")\n{\n    // Test case 1: Save state with both memory limits\n    std::string json_str = R"({"name": "John", "age": 30, "city": "New York"})";
    json::input_adapter_t ia(json_str);\n    json::parser<json> parser(std::move(ia));\n    \n    // Set both memory limits\n    parser.set_memory_limit(1024 * 1024);\n    parser.set_relative_memory_limit(0.5);\n    \n    // Save state\n    auto state = parser.save_state();\n    \n    // Check that both memory limits are saved\n    CHECK(state.memory_limit == 1024 * 1024);\n    CHECK(state.relative_memory_limit == 0.5);\n    \n    // Test case 2: Restore state with both memory limits\n    std::string json_str2 = R"({"name": "Jane", "age": 25, "city": "London"})";
    json::input_adapter_t ia2(json_str2);\n    json::parser<json> parser2(state, std::move(ia2));\n    json result2;\n    \n    // Parse the JSON\n    parser2.parse(false, result2);\n    \n    // Check that the result is correct\n    CHECK(result2["name"] == "Jane");\n    CHECK(result2["age"] == 25);\n    CHECK(result2["city"] == "London");\n}\n\nTEST_CASE("parse state with large JSON")\n{\n    // Create a large JSON string\n    std::string json_str = "{";
    for (int i = 0; i < 1000; ++i)\n    {\n        json_str += R"("key")" + std::to_string(i) + R"(: "value")" + std::to_string(i) + R"(")";
        if (i < 999)\n        {\n            json_str += ",";
        }\n    }\n    json_str += "}";\n    \n    // Parse the large JSON\n    json::input_adapter_t ia(json_str);\n    json::parser<json> parser(std::move(ia));\n    json result;\n    \n    // Save state during parsing\n    auto state = parser.save_state();\n    \n    // Parse the JSON\n    parser.parse(false, result);\n    \n    // Check that the result has 1000 elements\n    CHECK(result.size() == 1000);\n    \n    // Check that the first element is correct\n    CHECK(result["key0"] == "value0");\n    \n    // Check that the last element is correct\n    CHECK(result["key999"] == "value999");\n}